Run tests on CI
usagov/pangolin pull request #36
Opened 2021-12-02 01:29 UTC by hartsick

* Run on every push for now, to test

2021-12-02 14:34 UTC, rahearn requested changes
We can simplify this a bit by letting the setup steps handle dependency cacheing

2021-12-02 14:34 UTC, rahearn commented on .github/workflows/test.yml
> +    - name: Cache Gems
[suggestion] The `Setup Ruby` step can do this for us. See https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/blob/e9452643d5d672c47a94fe9e44b86bf09bcf33ef/.github/actions/setup-project/action.yml#L10 for an example.

2021-12-02 14:34 UTC, rahearn commented on .github/workflows/test.yml
> +    - name: Install and configure bundler
[suggestion] This step is also unnecessary if we have `setup-ruby` handle it.

2021-12-02 14:34 UTC, rahearn commented on .github/workflows/test.yml
> +    - name: Yarn cache
[suggestion] `setup-node` will cache by default, though not run `yarn install` for us. See https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/blob/e9452643d5d672c47a94fe9e44b86bf09bcf33ef/.github/actions/setup-javascript/action.yml for an example

2021-12-06 17:35 UTC, closed without merging

2021-12-06 17:36 UTC, hartsick commented
Closing since we have a lot of this infrastructure now! Will resubmit off latest main